# ============================================================
# CI Pipeline: OpenAPI Client Auto-Generation
# Trigger: When backend OpenAPI specs change (on push to main)
# ============================================================

name: OpenAPI Client Generation

on:
  push:
    branches: [main]
    paths:
      - 'ecossistema-sgc-backend/src/main/java/**/controller/**'
      - 'ecossistema-sgc-backend/src/main/java/**/dto/**'
      - 'ecossistema-si-backend/src/main/java/**/controller/**'
      - 'ecossistema-si-backend/src/main/java/**/dto/**'
      - 'ecossistema-wn-backend/src/main/java/**/controller/**'
      - 'ecossistema-wn-backend/src/main/java/**/dto/**'
      - 'ecossistema-gpj-backend/src/main/java/**/controller/**'
      - 'ecossistema-gpj-backend/src/main/java/**/dto/**'
  workflow_dispatch:

env:
  OPENAPI_GENERATOR_VERSION: '7.4.0'
  NODE_VERSION: '20'
  JAVA_VERSION: '21'

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: sgc
            port: 8081
            backend: ecossistema-sgc-backend
          - name: si
            port: 8082
            backend: ecossistema-si-backend
          - name: wn
            port: 8083
            backend: ecossistema-wn-backend
          - name: gpj
            port: 8084
            backend: ecossistema-gpj-backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install OpenAPI Generator CLI
        run: npm install -g @openapitools/openapi-generator-cli@${{ env.OPENAPI_GENERATOR_VERSION }}

      - name: Start ${{ matrix.service.name }} backend
        working-directory: ${{ matrix.service.backend }}
        run: |
          ./mvnw spring-boot:run -Dspring-boot.run.profiles=openapi &
          echo "Waiting for ${{ matrix.service.name }} to start on port ${{ matrix.service.port }}..."
          for i in $(seq 1 60); do
            if curl -sf http://localhost:${{ matrix.service.port }}/actuator/health > /dev/null 2>&1; then
              echo "Service is ready!"
              break
            fi
            sleep 2
          done

      - name: Download OpenAPI spec
        run: |
          curl -sf http://localhost:${{ matrix.service.port }}/v3/api-docs \
            -o ecossistema-docs/openapi/specs/${{ matrix.service.name }}-openapi.json

      - name: Generate TypeScript-Angular client
        run: |
          openapi-generator-cli generate \
            -c ecossistema-docs/openapi/configs/${{ matrix.service.name }}.json \
            --skip-validate-spec

      - name: Verify generated files
        run: |
          ls -la ecossistema-docs/openapi/generated/${{ matrix.service.name }}-client/src/
          echo "--- Model types ---"
          head -50 ecossistema-docs/openapi/generated/${{ matrix.service.name }}-client/src/model.ts || true

      - name: Upload generated client
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service.name }}-client
          path: ecossistema-docs/openapi/generated/${{ matrix.service.name }}-client/

  commit-clients:
    needs: generate-clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all client artifacts
        uses: actions/download-artifact@v4
        with:
          path: ecossistema-docs/openapi/generated/

      - name: Move artifacts to correct locations
        run: |
          for svc in sgc si wn gpj; do
            if [ -d "ecossistema-docs/openapi/generated/${svc}-client/${svc}-client" ]; then
              cp -r "ecossistema-docs/openapi/generated/${svc}-client/${svc}-client/"* \
                    "ecossistema-docs/openapi/generated/${svc}-client/"
              rm -rf "ecossistema-docs/openapi/generated/${svc}-client/${svc}-client"
            fi
          done

      - name: Commit updated clients
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ecossistema-docs/openapi/generated/ ecossistema-docs/openapi/specs/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto-regenerate OpenAPI TypeScript clients"
            git push
          fi
